In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

np.random.seed(42)
df = pd.read_csv('dataframe/WineQT.csv')

In [4]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4

In [6]:
columns_desejadas = ['fixed acidity', 'volatile acidity', 'residual sugar', 'alcohol', 'pH', 'quality']
df_selectionado = df[columns_desejadas]
print(df_selectionado.isnull().sum())
df_selectionado = df_selectionado.dropna()

fixed acidity       0
volatile acidity    0
residual sugar      0
alcohol             0
pH                  0
quality             0
dtype: int64


In [9]:
X = df_selectionado.drop('quality', axis=1)
y = df_selectionado['quality']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

In [11]:
acuracia = accuracy_score(y_test, y_pred)
print(f"Acurácia do modelo: {acuracia:.2f}")

print("\nMatriz de Confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))

Acurácia do modelo: 0.69

Matriz de Confusão:
[[ 0  3  3  0  0]
 [ 0 75 20  1  0]
 [ 0 24 69  6  0]
 [ 0  1 10 15  0]
 [ 0  0  2  0  0]]

Relatório de Classificação:
              precision    recall  f1-score   support

           4       0.00      0.00      0.00         6
           5       0.73      0.78      0.75        96
           6       0.66      0.70      0.68        99
           7       0.68      0.58      0.62        26
           8       0.00      0.00      0.00         2

    accuracy                           0.69       229
   macro avg       0.41      0.41      0.41       229
weighted avg       0.67      0.69      0.68       229



C:\Users\luizf\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\luizf\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\luizf\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [12]:
print("\n### Considerações Finais ###")
print("O projeto visa construir um modelo de Machine Learning utilizando Random Forest para prever a qualidade de vinhos")
print("com base em suas características químicas. A partir de um conjunto de dados, o modelo aprende padrões e faz previsões,")
print("permitindo análises e melhorias no processo de classificação".format(acuracia))


### Considerações Finais ###
O projeto visa construir um modelo de Machine Learning utilizando Random Forest para prever a qualidade de vinhos
com base em suas características químicas. A partir de um conjunto de dados, o modelo aprende padrões e faz previsões,
permitindo análises e melhorias no processo de classificação
